// Nom du pays dans sa/ses langue(s) locale(s), pour affichage bilingue
// (français / langue locale) sous les drapeaux.
export const LOCAL_NAMES = {
  allemagne: "Deutschland",
  andorre: "Andorra",
  autriche: "Österreich",
  belgique: "België",
  bulgarie: "България",
  chypre: "Κύπρος",
  croatie: "Hrvatska",
  espagne: "España",
  estonie: "Eesti",
  finlande: "Suomi",
  france: "France",
  grece: "Ελλάδα",
  irlande: "Éire",
  italie: "Italia",
  lettonie: "Latvija",
  lituanie: "Lietuva",
  luxembourg: "Lëtzebuerg",
  malte: "Malta",
  monaco: "Monaco",
  "pays-bas": "Nederland",
  portugal: "Portugal",
  "saint-marin": "San Marino",
  slovaquie: "Slovensko",
  slovenie: "Slovenija",
  vatican: "Vaticano",
};
